language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - ree
before_script:
  - 'git clone git://github.com/puppetlabs/puppetlabs-stdlib.git spec/fixtures/modules/stdlib'
env:
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.18
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.14
